In [8]:
import numpy as np
val1, val2, val3 = np.loadtxt('dados.txt', skiprows=1, unpack=True)
print(val1)

[ 0.1212  0.104   0.5661  0.762 ]


In [11]:
# Carregando dados e sobrescrevendo valores faltantes
my_array = np.genfromtxt('dados2.txt', skip_header=1, filling_values=-999)
print(my_array)

[[  1.21200000e-01   8.42000000e-01   3.67200000e-01]
 [ -9.99000000e+02   5.42200000e-01   3.45510000e-01]
 [  5.66100000e-01   9.32000000e-01  -9.99000000e+02]
 [  7.62000000e-01   8.47361000e-01   1.53800000e-01]]
