In [4]:
import numpy as np

m1 = np.array([[3, 4, 1], [1, 3, 5]])
m2 = np.array([[8, 7, 6], [1, 3, 4]])

# Arredondamento da matriz
np.matrix.round(m1 / m2)

array([[ 0.,  1.,  0.],
       [ 1.,  1.,  1.]])

In [6]:
m1 + m2

array([[11, 11,  7],
       [ 2,  6,  9]])

In [8]:
m1 * m2

array([[24, 28,  6],
       [ 1,  9, 20]])

In [10]:
m1 - 3

array([[ 0,  1, -2],
       [-2,  0,  2]])