In [22]:
#! /usr/bin/env python3
# -*- coding:utf-8 -*-
import numpy as np

# The numpy
mat = np.array([[4, 2, 3], [4, 6, 8]])

In [34]:
joao_pts = [2, 43, 11, 22, 4]
marcos_pts= [2, 5, 1, 6, 33]
alicia_pt= [20, 40, 20, 43, 22]
pessoas = np.array([joao_pts, marcos_pts, alicia_pt])
# Criando um array
mydata = np.arange(0, 20)
mat1 = np.reshape(mydata, (5, 4))
print(mat1) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [36]:
mat1.item(3)

3